### ISSUE TITLE
Multiple links in one URL field

### ISSUE THREAD

**Issue by shackrock** [pfn/keepasshttp#107]
I was hoping I'd be able to add multiple links in a single URL field.  For example:

citicards.com, citibank.com, citi.com

And have the plugin check all 3... is anything like this possible? 

Thanks!

**Comment by LatinSuD** [comment]
Could it be possible to use URL fields like WebAutotype?

With this syntax you only need one Keepass entry, and in the "Auto-Type" tab put additional URL in a special format similar to this:

??:URL:https://citi.com
??:URL:https://citibank.com

And so on.
