### ISSUE TITLE
Incompatible with the latest version of KeePass2.

### ISSUE THREAD

**Issue by maxolasersquad** [pfn/keepasshttp#158]
KeePass 2.25 refuses to load the plugin stating it is incompatible.
![keepasshttp](https://cloud.githubusercontent.com/assets/177150/2777154/951d600c-cae0-11e3-95f7-d947344e0e1a.png)

**Comment by loostro** [comment]
@jmontiel Thanks a lot. That fixed it for me. `KeePassHttp.plgx` must be readable by current user.

**Comment by TraceyC77** [comment]
Thanks, @jmontiel. I ran into the same error, and changing permissions on KeePassHttp.plgx solved the problem for me as well.

**Comment by sixspot** [comment]
I'm gonna drop a comment here, even though this is closed. Selfishly enough, it will probably help me the next time around. This incompatible plugin thing pops up now and then even though nothing has changed with versions.  Check ps for "`/usr/bin/cli /usr/lib/keepass2/KeePass.exe" or so and and kill them all.  That fixed things for me several times.

**Comment by DaSpawn** [comment]
just hit this as well, false error, carestad and sixspot issue of keepasss still running was what I had also.  Killed the proc then error was gone.

**Comment by ffflorian** [comment]
Thanks @sixspot, that was actually my problem, too.
