### ISSUE TITLE
KeePass crashes on Ubuntu when using ChromIpass

### ISSUE THREAD

**Issue by syphernl** [pfn/keepasshttp#159]
I am using a combination of ChromIPass and Chromium (35 I believe) and Firefox 28 with KeeFox on Ubuntu 14.04. 
With Firefox it works fine, but when I launch Chrome KeePass crashes.

This was not happening before I upgraded to 14.04 (or when Chrome was upgraded?) and is rather annoying. Running keepass from CLI does not show and reasons for it happening.

**Comment by danieljcosta** [comment]
This problem only occours when using a database with special char's (i.e. shared with windows pc).
After a lot of dependencies, I found that nothing work's. A quick test is just to cancel auth, and keepass open without any error but with a blank new db.

My only solution was move to KeePassX that is compatible with my DB without any error or workarround.

This seems to be a bug related with mono libs, but, who knows when this will be solved....

**Comment by holstf** [comment]
I ran into the same problem on  Ubuntu 16.04 with keepass 2.32 and KeePassHttp.plgx 1.8.4.1. Had the message:
`[xcb] Too much data requested from _XRead... etc.`

Installing `mono complete` and doing `sudo apt-get install libmono-system-xml-linq4.0-cil libmono-system-data-datasetextensions4.0-cil libmono-system-runtime-serialization4.0-cil mono-mcs` was not enough. 

The comment by  @MarkJaroski  put me on the right track. `libmono-system-data-linq2.0-cil` is not available in the newer mono version as included in Ubuntu 16.04 but there is a replacement:
`apt-get install mono-reference-assemblies-2.0`

That was for me the final step getting it working again.
