### ISSUE TITLE
Basic-Authentication on same URL

### ISSUE THREAD

**Issue by boesing** [pfn/keepasshttp#167]
Hey guys,

I have the same domain with different path and different Basic-Authentication credentials.
Actually it seems that KeePassHTTP only returns the first matching URL (without path obviously) credentials.
I tested the ordering in KeePass 2 and toggled positions of both password entries so I can confirm that definitely the first matching URL is used to fill in .htaccess passwords.

domain1.com/foo user:foo pass:bar
domain1.com/bar user:bar pass:foo

So when I call domain1.com/bar it gets filled in the "foo" pw "bar" user which fails and therefore showing the basic authentication popup to fill in correct credentials.
Is there a reason why the full URL matching does not work for .htaccess (Basic-Authentication) URLs?

Hope you can fix that, thanks in advance!

**Comment by obillard** [comment]
Hi,
Is there anything that can be done to prioritize credentials selection in basic auth, between entries linked to the same domain ?
