### ISSUE TITLE
Attempted to read or write protected memory. This is often an indication taht other memory is corrupt

### ISSUE THREAD

**Issue by xinbenlv** [pfn/keepasshttp#194]
![error](https://cloud.githubusercontent.com/assets/640325/5697551/da9e856a-99a8-11e4-85c9-279a9bc30cdc.png)
UnsafeNativeNclMethods.SetFileCompletionNotificationModes

**Comment by xinbenlv** [comment]
No one experienced this?

**Comment by v1klng** [comment]
Im getting this error too. Several attempts of uninstalling and reinstalling keepass and keepasshttp didnt work.
![image](https://cloud.githubusercontent.com/assets/10595483/5798079/183c2d98-9fc4-11e4-8567-a581eeb70460.png)

**Comment by xinbenlv** [comment]
I realize it is caused by Astrill

**Comment by v1klng** [comment]
Do you have a fix for this error ?

BTW what is Astrill ?

**Comment by xinbenlv** [comment]
Astrill is a VPN I installed. astrill.com
When I uninstall it, and clean up the cached KeepassHttp, it works.



Zainan Victor Zhou 周载南
Software Engineer at Google
Email: zzn@zzn.im
Phone: (650) 336-5691
微信号（WeChat ID） xinbenlv
Alumni of Tsinghua, Hopkins, Microsoft Research Asia
Linkedin www.linkedin.com/in/zainanvictorzhou

**Comment by v1klng** [comment]
Ah ok thx for the info. But I dont have that installed.

**Comment by xinbenlv** [comment]
Since I discovered the incompatible software which is Astrill, you might have some similar software that is causing that kind of incompatibility. I recommend you find the programs who might be the culprit.

**Comment by xinbenlv** [comment]
you can try to see if it is caused by some other software that you installed


Zainan Victor Zhou 周载南
Software Engineer at Google
Email: zzn@zzn.im
Phone: (650) 336-5691
微信号（WeChat ID） xinbenlv
Alumni of Tsinghua, Hopkins, Microsoft Research Asia
Linkedin www.linkedin.com/in/zainanvictorzhou

**Comment by zanderfray** [comment]
I can confirm that astrill VPN causes this problem, I was having the same issue, after removing Astrill keepasshttp works correctly again.

**Comment by therompalace** [comment]
Same here. I don't have astrill installed but am still getting the same error.
