### ISSUE TITLE
Does keepass have to be open and unlocked for this to work?

### ISSUE THREAD

**Issue by togakangaroo** [pfn/keepasshttp#208]
I am using keepasshttp with the chrome extension. It seems like it only works when keepass is open and unlocked.

I'm confused if that's the intended behaviour. If so, that means I have to have my password file unlocked on my computer at all times if I want it to be usable. Isn't this even worse from a security perspective than using the clipboard?

Is there some other thing that can be done?

**Comment by pfn** [comment]
What would be the point if the browser can access your passwords while your
database is locked?

**Comment by togakangaroo** [comment]
I was thinking that locking the db might be some sort of mode where it's just the UI is locked but it keeps running in the background.

It concerns me leaving it open. If I get my PC stolen while it's on someone would just have the windows password in between them and all my top secret passwords

**Comment by pfn** [comment]
Set keepass to auto-lock on inactivity.

**Comment by togakangaroo** [comment]
I see, not perfect since I basically have to type my keepass password every time I need any password but I guess it is what it is and it's not your guys' fault.

Thanks for taking the time to explain this to me.
