### ISSUE TITLE
Stopped working after I update KeePass to 2.29

### ISSUE THREAD

**Issue by ErtugKaya** [pfn/keepasshttp#213]
I updated KeePass from 2.28 to 2.29 and KeePassHttp stopped working. I cannot see it in the plugins list.

I downloaded .plgx file again but no luck.

Is it just me or a general problem?

PS: I use Win 7 64bit.

**Comment by pfn** [comment]
Just you, I'm using the same versions without issue.

--

**Comment by ErtugKaya** [comment]
Thank you.

**Comment by digantdesai** [comment]
Stopped working !!!

**Comment by ErtugKaya** [comment]
If memory serves, I resolved that by doing those:

In KeePass main menu select Tools - Plugins. A new window will open.

Click Clear button in Plugin Cache area. 

Reinstall the plugin if necessary.

HTH.

Ertug
