### ISSUE TITLE
Incompatability with KeePass 2.29

### ISSUE THREAD

**Issue by TheFragen** [pfn/keepasshttp#214]
Running Windows 8.1 64 bit
Keepass 2.29
Newest KeePassHTTP

The plugin doesn't show up in the new version of KeePass .

Measures tried so far:
1. Uninstalling KeePassHTTP, restarting the computer, installing KeePassHTTP again.
2. Uninstalling KeePass and deleting all leftovers, uninstalling KeePassHTTP. Then installing everything again.

I've only gotten it to work again, by reverting to KeePass 2.28.

**Comment by TheFragen** [comment]
Turned out it was a Chocolatey problem. KeePassHTTP was installed into the wrong folder.

Please ignore this issue, and continue the good work.

**Comment by kendaleiv** [comment]
@TheFragen Would you mind creating an issue for the [keepass-keepasshttp](https://chocolatey.org/packages/keepass-keepasshttp) Chocolatey package at https://github.com/kendaleiv/chocolatey-keepass-keepasshttp/issues?

I haven't been able to reproduce this issue.
