### ISSUE TITLE
.NET HttpListener not supported

### ISSUE THREAD

**Issue by holygoatnickels** [pfn/keepasshttp#223]
So the application was working fine yesterday, and when I booted up and launched keepass, I get the following error.  Does anyone know what I could check to figure out what is causing the issue?

Windows 7 x64
Keepass v2.29
keepasshttp v1.8.4.0

Error:
-----
.NET HttpListener not supported
The .NET HttpListener is not supported on your OS

**Comment by holygoatnickels** [comment]
I was messing around with getting Apache running on my machine and in that process disabled the HTTP windows service which I am guessing this plugin relays on.  Once I enabled that service and reboot the keepasshttp plugin launched fine.  I guess I will have to find another solution for Apache.

**Comment by TARehman** [comment]
I'd like to raise this again; it just happened to me. I'm on a work computer and I have a suspicion that something caused this based on my using this laptop remotely, rather than docked; it would be helpful to narrow down what it is. The issue just appeared after using the software yesterday with no issues.

**Comment by TARehman** [comment]
A very brief update: the error goes away when I "Run As Administrator" in Windows 7, but otherwise reappears. Very unusual.

**Comment by TARehman** [comment]
@pfn Just tagging you in case closed issues don't attract attention...sorry if it spams you.

**Comment by TARehman** [comment]
Sorry. This appears to have spontaneously resolved when I did a repair install of Virtualbox. I can only conjecture that it had something to do with the drivers that Virtualbox uses to connect to the guest OSes. I don't even think I could replicate it if I tried.
