### ISSUE TITLE
Many websites don't correctly detect auto-filled usernames/passwords.

### ISSUE THREAD

**Issue by otac0n** [pfn/keepasshttp#226]
There are many sites that listen for `keydown` instead of `change` events, etc.  For compatibility, would it be possible to emulate a user to the largest extent possible?  (e.g. Click, Press Key, Press Key...)

**Comment by sirlancelot** [comment]
This should be filed as an issue for the specific browser extension you are using. It has nothing to do with KeePassHttp plugin.

**Comment by otac0n** [comment]
My bad, I meant to open this against PassIFox.
