### ISSUE TITLE
KeePassX support ?

### ISSUE THREAD

**Issue by tuxayo** [pfn/keepasshttp#238]
I can't find if it's compatible with KeePassX?

**Comment by fcore117** [comment]
I would like to use Chromium with KeePassX too because it is lighter and cross platform QT version.

**Comment by pfn** [comment]
File an issue on the keepassx tracker

**Comment by tuxayo** [comment]
Thanks.

For other people ending up also here by error:
There is already an [issue](https://www.keepassx.org/dev/issues/91) and a [pull request (not ready yet)](https://github.com/keepassx/keepassx/pull/111).
