### ISSUE TITLE
dosen't work on keepass2.30 on ubuntu 14.04LTS

### ISSUE THREAD

**Issue by kowenzhang** [pfn/keepasshttp#239]
i installed this plugin on my win 7 notebook with keepass2.30 and it runs perfectly. But it came out with a compatibility problem when i copy it to my ubuntu pc  which  also intalled keepass 2.30. The alert message is as bellow:

![keepasshttp-bug](https://cloud.githubusercontent.com/assets/1937655/10903413/5009bfc0-8244-11e5-891c-ddf7ec4c1b9b.jpg)

**Comment by markuskeunecke** [comment]
I have the same issue on my Ubuntu 15.04 running Keepass 2.30 and KeePassHttp 1.84.

**Comment by nifr** [comment]
install `mono-complete` ... then reboot.

**Comment by markuskeunecke** [comment]
Reboot on an Ubuntu?

**Comment by ianchanning** [comment]
On Linux Mint running `sudo apt-get install mono-complete` *and then a reboot* as suggested by @nifr worked.

**Comment by markuskeunecke** [comment]
I was just suprised by having to reboot on an Ubuntu as I am not used to that. But I can confirm, that a reboot solves the issue.

**Comment by kowenzhang** [comment]
installing mono-complete and reboot sovled my problem, thanks guys!

**Comment by kowenzhang** [comment]
Another question. Can I access the keepasshttp service via network from a remote pc? 
I configured a remote chromeipass, but when i clicked connect, nothing happened. 
When i use chromeipass on local pc and click the connect button , keepass  pops up a confirm window for use to name the connection.

**Comment by ianchanning** [comment]
@kowenzhang you should ask that on a separate issue

**Comment by kowenzhang** [comment]
@ianchanning  thanks for reminding

**Comment by borisiceman** [comment]
I have the same issue on my Manjaro  running Keepass 2.30. KeePass  didn't recognized KeePassHttp 1.84  as plugin.  Mono 4.2.2.10-1 installed from AUR, rebooted. Another instance KeePass work well at FireFox (KeeFox).  such combination work well from win8 to win10 more than 2 yrs.
