### ISSUE TITLE
On AliExpress.com not work

### ISSUE THREAD

**Issue by rinaatt** [pfn/keepasshttp#244]
Not to expose login and password on aliexpress.com site.
![2015-12-08 12-14-47](https://cloud.githubusercontent.com/assets/6111202/11649889/b0c7ff9e-9da5-11e5-9d98-ece60c224535.png)
![2015-12-08 12-16-10](https://cloud.githubusercontent.com/assets/6111202/11649892/b43b7ebc-9da5-11e5-8131-47d9b5338713.png)

**Comment by pfn** [comment]
Don't know why it fails, but if you set the title to aliexpress.com it will
work fine

--

**Comment by rinaatt** [comment]
No, so doesn't work too.

**Comment by rinaatt** [comment]
I understand. It turns out, it is in the form of login located in "iframe" tag with other url.

![2015-12-09 10-44-27 developer tools - https login aliexpress com buyer_ru htm spm 2114 11020108 1000002 4 9upmfy return h](https://cloud.githubusercontent.com/assets/6111202/11677661/0c1aff9c-9e62-11e5-9ff5-cc3c76f2c683.png)

**Comment by pfn** [comment]
Thanks for digging. I would label this a faq and not a bug.

--

**Comment by skobkin** [comment]
You must use `https://passport.alibaba.com/` URL in KeePass for Aliexpress entry.
