### ISSUE TITLE
Feature request: Change save location of stored credentials

### ISSUE THREAD

**Issue by Noloxs** [pfn/keepasshttp#246]
Hi.

I am not sure if this is the correct place to do this, so sorry for any inconvenience if not.

I would think a valuable feature to implement would be the possibility to change the location credentials are saved instead of the predefined group: "KeePassHttp Passwords"

**Comment by pfn** [comment]
You can move them after they're saved. It's just a placeholder to save
into.

**Comment by Noloxs** [comment]
I know this, but I usually just move the keys to another folder and delete the default folder. 

It is not a critical feature, just that it would be a nice possibility to have.
