### ISSUE TITLE
What license is KeePassHttp distributed under?

### ISSUE THREAD

**Issue by Pastafarianist** [pfn/keepasshttp#247]
I've written a [Gentoo ebuild](https://github.com/maksbotan/maksbotan_overlay/blob/cdeb004ca5e118ec79da4e309ae28b67dac5e9d9/app-admin/keepasshttp/keepasshttp-9999.ebuild#L11) for KeePassHttp, and it's almost complete with one exception: it does not contain license information. I haven't been able to find anything relevant in the repository. Which license is KeePassHttp distributed under?

**Comment by nifr** [comment]
I'd like to know this too, could provide a ppa/package for ubuntu.

**Comment by pfn** [comment]
gplv3

**Comment by nifr** [comment]
Wow that was quick - thanks for the quick response :+1:

**Comment by Pastafarianist** [comment]
Thank you. I've updated the ebuild.
