### ISSUE TITLE
Allow multiple instance

### ISSUE THREAD

**Issue by andras-tim** [pfn/keepasshttp#255]
I can not use KeePass with KeePassHttp on Windows Terminal server environment, because KeePassHttp always listens on its fixed port. Only the first user can use this plugin.

I know, this is a technical limitation now, however, can you workaround with make the port number customizable? Or why not use pipes for Inter-process communication?

**Comment by nifr** [comment]
The port is actually configurable. Go to **Tools -> KeePassHttp Options -> Advanced **.

![screen shot 2016-03-19 at 13 10 27](https://cloud.githubusercontent.com/assets/851258/13897020/3c52b15c-edd4-11e5-93e6-665725255b81.png)

**Comment by andras-tim** [comment]
Oh. Thank you for your help!
