### ISSUE TITLE
Username+Passwort Shortcut not working 

### ISSUE THREAD

**Issue by dasbillgh** [pfn/keepasshttp#263]
Hello,

since the new update STRG + SHIFT + P / STRG + SHIFT + F6 not working anymore.
Is there a new Shortcut or is it a bug?

Thanks for reply.

**Comment by pfn** [comment]
Ctrl shift u and p as documented

**Comment by dasbillgh** [comment]
CTRL + SHIFT + P are working but CTRL + SHIFT + u will not working.
Any idea why?

**Comment by dasbillgh** [comment]
I solved it now, it was a problem with CTRL + SHIFT + u under Ubuntu.
It's a known bug: https://www.google.de/#q=ctrl+shift+u+ubuntu

Thanks for your support and your great work!
