### ISSUE TITLE
ChromeIPass cannot connect to Keepass with Tor.

### ISSUE THREAD

**Issue by radek-sprta** [pfn/keepasshttp#266]
Throws ERR_SOCKS_CONNECTION_FAILED. However, works without a problem when not using the Tor proxy. Is there something I have to reconfigure in ChromeIPass/Keepass-http to make it work, or is it an issue with my Tor configunation/not possible?

Using keepass 2.29, ChromeIPass 2.7.1, keepasshttp 1.8.4.1

**Comment by pfn** [comment]
remove proxy setting for localhost; i.e. do not use proxy for localhost
connections.

**Comment by radek-sprta** [comment]
So the problem was I had the wrong port in browser settings. Went directly through Tor instead of Privoxy. And I thought I checked everything >.<
