### ISSUE TITLE
Version compatible to KeePass2 2.32 (Ubuntu 15.10)?

### ISSUE THREAD

**Issue by AntonStoeckl** [pfn/keepasshttp#267]
Hi there,

currently the PPA for KeePass2 has only version 2.32. Seems to be a dev version, but it's the only one available for Ubuntu 15.10.
That's not compatible with the latest version of KeePassHttp (1.8.4.1)

Will there be a 1.8.4.2 soon?

Currently I have no sane way to install a working combination on Ubuntu 15.10 :-(

**Comment by laoneo** [comment]
It is also not compatible on the LTS version 16.04.

**Comment by Spocklw** [comment]
Try installing mono-complete again, it probably got uninstalled with the update.

**Comment by laoneo** [comment]
Indeed it worked. Think issue can be closed.

**Comment by AntonStoeckl** [comment]
Sadly, this only works on Ubuntu 16.04 for me.

On Ubuntu 15.10 with KeePass2 2.32 from PPA and with 2.29 from regular Ubuntu repo it does not work. I have installed mono-complete and I have tried the latest version of KeePassHttp.plgx + 2 other versions  I have still on my computer. All sorts of mono libs are different on those 2 Utuntu versions, guess that's the reason.

Please also note that 2.29 worked until yesterday or so. Today KeePass crashed and on restart it says that Plugin is not compatible. I guess some lib (probably mono ...) was updated.

Case anybody knows a working combination on Ubuntu 15.10, please let me know.

I'm really sad, this is ongoing tragedy. Every couple of months the plugin stops to work. :-(
