### ISSUE TITLE
Keypasshttp not working on the new Microsoft login page

### ISSUE THREAD

**Issue by JayBeeDe** [pfn/keepasshttp#270]
Hi,

Since several days Microsoft has update the login page which seems to be not compatible with keypasshttp. Keypasshttp autofill doesn't work on the following website: check by yourself:
[https://login.live.com/](https://login.live.com/)

I'm using Google Chrome v49.0.2623.110 m (64-bit) and KeypassX v2.32 on Microsoft Windows 10. I've tested with all other extensions disabled (Adblock, etc.), except the keypasshttp extension (v1.8.4.1)!

**Comment by pfn** [comment]
works for me

**Comment by JayBeeDe** [comment]
Sorry but no it doesn't work (on my work Laptop and personal Laptop)
The plugin gives the password and fulfills the form, but then when you click login it fails.
Credential are correct (when I do it manually or with the "Perform Auto Type" function from KeypassX, it works).

It seems to be a style conflict, because the suggestions appear in blue, not as other websites...
See screenshot: [http://postimg.org/image/5akfry53r/](http://postimg.org/image/5akfry53r/)

**Comment by pfn** [comment]
it's one of those forms where it needs to detect a letter was typed. if
someone wants to fix this, I'll take a PR.
