### ISSUE TITLE
Windows: Chocolatey warning

### ISSUE THREAD

**Issue by asoplata** [pfn/keepasshttp#284]
Upon using Powershell (with Admin priv) to upgrade from keepasshttp 1.8.4.0 to 1.8.4.1, I got the following warning: `WARNING: Write-ChocolateySuccess is deprecated. If you are the maintainer, please remove it from your package file.`

The upgrade still worked, but I wanted to pass on this deprecation warning.

Thanks for all your great work!
Austin

**Comment by kendaleiv** [comment]
There's an open issue for this at https://github.com/kendaleiv/chocolatey-keepass-keepasshttp/issues/3.

**Comment by asoplata** [comment]
Sorry about that; I tried to search for similar issues but didn't see that one. Closing this.

**Comment by kendaleiv** [comment]
No worries, I wouldn't have expected you to know about that -- it's a totally different repository!
