### ISSUE TITLE
Help with creating a Java compatible version ...

### ISSUE THREAD

**Issue by jorabin** [pfn/keepasshttp#290]
Hi

This is great. But I don't use Windows. So I created a Java backend implementation of KeePass called [KeePassJava2](https://github.com/jorabin/KeePassJava2). I would like to add HTTP support as provided here, but am a bit confused about how it is supposed to work (I'm a Java rather than a C# wonk). Would appreciate offline help. Twitter @jorabin. I'd be grateful. 

Thanks!

**Comment by pfn** [comment]
I wrote keepassj as a direct port of keepasslib to java a while ago. Anyway
c# looks generally like java and should be able to port pretty easily.
Mainly you'll need an http server and json implementation of your choice.
Otherwise it should be straightforward

**Comment by jorabin** [comment]
Thanks for your reply. Kudos re keepassj, I wanted something that was not a direct port, hence did my own thing.

Re porting keepasshttp, the json stuff and http server stuff is not a problem, what is making me scratch my head is the cryptography, namely understanding TestRequestVerifier (below).

I apologise in advance if I am being really stupid.

I am getting an associate request which looks like

`{"RequestType":"associate","Key":"WQISYVajkviMNaSBIaUTgZbUaJD1RujU6eoh3B89+lc=","Nonce":"V2bJ4VFRrbH+oUd0W8swjQ==","Verifier":"oegZmDzOLFVv8jAYxfnOqBk+0KiasSr6J/8v9xbUIkE="}`

The nonce is 16 bytes when decoded, the other values are 32 bytes. In the following code aes is presumably CBC PKCS ... after decryption buf presumably contains 32 bytes. It's then converted to a string and compared with the base64 encoded nonce? Would be grateful for any help.

thanks again

            private bool TestRequestVerifier(Request r, Aes aes, string key)
        {
            var success = false;
            var crypted = decode64(r.Verifier);

            aes.Key = decode64(key);
            aes.IV = decode64(r.Nonce);

            using (var dec = aes.CreateDecryptor())
            {
                try {
                    var buf = dec.TransformFinalBlock(crypted, 0, crypted.Length);
                    var value = Encoding.UTF8.GetString(buf);
                    success = value == r.Nonce;
                } catch (CryptographicException) { } // implicit failure
            }
            return success;
        }

**Comment by pfn** [comment]
nonce is effectively IV; decrypt the verifier using the associated key with
the nonce as IV and confirm that it is the value of nonce.

i.e. `decrypt(iv, verifier) == nonce`; yes, it's aes256-cbc-pkcs5padding
(or 7 or whatever it is)

**Comment by jorabin** [comment]
Thanks very much.
