### ISSUE TITLE
KeePassHTTP return 404 when trying to download plugin for manual installation

### ISSUE THREAD

**Issue by phandox** [pfn/keepasshttp#305]
Hello,

Link provided in documentation is broken https://raw.github.com/pfn/keepasshttp/master/KeePassHttp.plgx returns 404 error.

Thanks for fixing it up.

**Comment by Christoph460** [comment]
Somehow there is the KeePassHttp.plgx file missing in the directory, It got lost with the [commit](https://github.com/pfn/keepasshttp/commit/07ea5ab8c52fcab62ffc410885349709d6081043) named "removes plgx from branch".

**Comment by 1mh0tep** [comment]
Hello,
And so, how can we download the KeePassHttp.plgx file ?
Please I really need to manual install.
Thanks

**Comment by iarp** [comment]
Until this is fixed, you should be able to download it from the commit itself. [Click on the Download button.](https://github.com/pfn/keepasshttp/blob/a92b3354eb19f516130f157de52b126308f7e6e9/KeePassHttp.plgx)

**Comment by 1mh0tep** [comment]
Thank you iarp !
