### ISSUE TITLE
Download link for plgx file is dead

### ISSUE THREAD

**Issue by ezmiller** [pfn/keepasshttp#307]
Your README refers to a `.plgx` file, but the file doesn't seem to exist in the project anymore. Is there now another installation process?

**Comment by pfn** [comment]
It's a mistake that will be remedied soon

**Comment by zeichenanonym** [comment]
Since this seems to take just a little time longer to resolve, I have fetched an old version from my laptop.
AFAIK this version is from Dec 24 2016 and is available without any promises at
https://storchris.blum.coffee/KeePassHttp.plgx
enjoy!

**Comment by pfn** [comment]
plgx has been updated, for future reference, you can always pull old versions from github https://github.com/pfn/keepasshttp/commits/master

also, it is always available from https://passifox.appspot.com/KeePassHttp.plgx
