### ISSUE TITLE
Security considerations

### ISSUE THREAD

**Issue by jrwolney** [pfn/keepasshttp#309]
Hi. I don't undersand completly this part: "...If a new client has to connect to KeePassHttp, the encryption key is generated and send to KeyPassHttp via an unencrypted connection..."

**Comment by Dunciboy** [comment]
When a new browser connect you are asked to create a new name for the new browser on your device essentially your encryption that will be used after that setup will be sent in plain text via local http and after that setup the key that was send over to the plugin will be saved within the plugin and used to communicate.

**Comment by jrwolney** [comment]
Thanks.
