### ISSUE TITLE
Security problem - KeePassHTTP protocol

### ISSUE THREAD

**Issue by darkneptune** [pfn/keepasshttp#310]
I found this info into the 'KeepassXC' web page: https://keepassxc.org/project

"

A note about KeePassHTTP

KeePassHTTP is not a highly secure protocol and has certain flaws which allow an attacker to decrypt your passwords if they manage to intercept communication between a KeePassHTTP server and PassIFox/chromeIPass over a network connection (see here and here). KeePassXC therefore strictly limits communication between itself and the browser plugin to your local computer. As long as your computer is not compromised, your passwords are fairly safe that way, but use it at your own risk! 

"

Could you please solve the security problem? 

Thanks, :)

**Comment by pfn** [comment]
There are conceptual security problems. Not practical problems.

"As long as your computer is not compromised" -- if your computer is compromised, your security game is over. Period.
