### ISSUE TITLE
Basic auth: Fill credentials but NOT auto-submit?

### ISSUE THREAD

**Issue by TjWallas** [pfn/keepasshttp#311]
Hi,

This is a sequel issue to #167 but a bit different.

Not only users might have different credentials for the same domain, they also might have domains with a common prefix stored in the keepass DB. This yields unwanted behavior whereby keepasshttp auto-submits and leaks stored credentials to a potentially mis-matching URL. Is there a possibility to autofill the credentials but NOT submit and wait for user input?

This allows the user to visually confirm the entered credentials (Well, at least the username) before keepasshttp sends anything over the wire. In addition, the use of the keepasshttp yellow tooltip at the bottom-right could aid the user confirm which keepass entry is being fetched (Just like the behavior with login forms).

I believe autosubmit should only be allowed if there is **only one** matching keepass entry and not many.

**Comment by pfn** [comment]
Not a keepasshttp issue. Browser plugins handle this. Chromeipass does auto
submit because auto fill is not possible.
