### ISSUE TITLE
Incompatible with Linux (can we have a port please?)

### ISSUE THREAD

**Issue by ghost** [pfn/keepasshttp#349]
I tried using ChromeIPass with KeePassHTTP in Chromium, on Linux Mint 18.3 (based on Ubuntu 16.04 w/ Cinnamon DE). I presume it doesn't work because of a dll file intended for Windows (though this may be provided for in Mono, idk?). A Linux port would be nice, to ensure cross-compatibility.

**Comment by quirinux** [comment]
Have you tried .plgx version?
It works like a charm with mono and keepass portable version, but mono is capable to read .net dll anyway

**Comment by dniku** [comment]
It is compatible with Linux. Check your distribution's packages or see instructions for manual installation [here](https://github.com/pfn/keepasshttp#non-windows--manual-windows-installation).

**Comment by juliantaylor** [comment]
The plugin is now also available as a debian package:
https://tracker.debian.org/pkg/keepass2-plugin-keepasshttp
