### ISSUE TITLE
Not compatitble with Keepass2 2.40

### ISSUE THREAD

**Issue by hydrian** [pfn/keepasshttp#379]
Upgraded to keepass2 via the jtaylor PPA. KeePassHttp doesn't seem to be compatible with the latest KPH  version in master.

**Comment by juliantaylor** [comment]
are you using keepasshttp from the ppa too? It is working for me with 2.40 on ubuntu 18.04

**Comment by hydrian** [comment]
You can ignore this. It was a bug caused by another plugin that causes KPH to try to run multiple instances of the web server on the same port and conflicting.
