### ISSUE TITLE
Incompatible to latest KeePass Version 2.41

### ISSUE THREAD

**Issue by togetheronthesand** [pfn/keepasshttp#382]

**Comment by togetheronthesand** [comment]
Unfortunately, KeePassHttp is no longer compatible to KeePass in Version 2.41
Reading previous posts, I know that you are too busy to maintain this beautiful plugin. :-(

I would love to see this beeing fixed, but maybe someone could recommend any (non-cloud) alternatives as well?

Some research left me where I am.
KeePass is still my preference, but as far as I can tell, does not integrate to Chrome without this plugin.

![image](https://user-images.githubusercontent.com/36489619/53546857-bf444400-3b2d-11e9-8df0-12738a3aaaa7.png)

Either way, big thanks for this great work!
Best
Christian

**Comment by rbolsius** [comment]
I'm using KeePass 2.41 Portable and KeePassHttp is working fine for me.  Perhaps you could try removing the KeepassHttp plugin, removing the N5jtgmLLjxfHufUKoxMb directory from the PluginCache, and then installing the KeepassHttp plugin again.

**Comment by togetheronthesand** [comment]
I have stopped KeePass, deleted the PluginCache and restarted.
It works just fine again. :-)

Thank you very much for your suggestion.

**Comment by karfau** [comment]
Under the Menu Tools > Plugins there is a button to clear the cache (no need to find it on the file system) then it will be rebuild on the next start. :tada:

**Comment by togetheronthesand** [comment]
This is well noted.
Many thanks.

But hey, why go easy when you can do it the hard way. ;-)
