### ISSUE TITLE
Incompatible with KeePass-2.42

### ISSUE THREAD

**Issue by mide22** [pfn/keepasshttp#384]
After updating KeePass-2.41 -> KeePass-2.42 I got this message:
![image](https://user-images.githubusercontent.com/32170723/57018783-f49c0980-6c24-11e9-9e76-40c724dc4a50.png)

$ md5sum KeePassHttp.plgx 
323af5ade1d47d375cf65bc9a52ac45f  KeePassHttp.plgx

// edit:
now I switched to https://keepassxc.org - works better with Linux than KeePass

**Comment by ArcticSnowman** [comment]
Raised a bug with KeePass as well.  This makes it a breaking release..

https://sourceforge.net/p/keepass/bugs/1843/

**Comment by Lorenzo-Thomas** [comment]
![KeePassHttp](https://user-images.githubusercontent.com/45856758/57023822-0c619680-6c01-11e9-9e1e-0e7893ae8108.png)

**Comment by mbutler755** [comment]
![2019-05-01 09_28_00-KeePass](https://user-images.githubusercontent.com/2465325/57028261-7ecb7a00-6bf3-11e9-947b-1a2e79a4dca1.png)

**Comment by mverzocc** [comment]
If you go to https://sourceforge.net/p/keepass/discussion/329220/thread/5ef408ed35/ you will
see that Dominik Reichl has posted an updated version of the KeePassHttp plugin (and somebody
else has used it and it works). I find this really unsatisfactory, because unless somebody steps in and maintains KeePassHttp this is likely to happen again. It looks like the people behind KeePassHttp have moved on to KeePassXC and are no longer maintaining KeePassHttp. The sad thing is that KeePass is the only thing that works on all platforms I use (including Android/Chrome), which KeePassXC doesn't (no idea whether it will do it in the future). For me KeePassHttp was part of the game. I may upgrade to that unsupported version and start planning for the next password manager.... :(

**Comment by aadler** [comment]
Thanks to Dominik for updating the plugin on his own; it's not his responsibility. I don't have the skills for it, but being that the plugin is FLOSS under the GPL3, someone can fork the project and maintain it.

**Comment by ComiR** [comment]
The patched version is available at https://keepass.info/filepool/KeePass_190501_KeePassHttp.zip
Via this post: https://sourceforge.net/p/keepass/discussion/329221/thread/de57e6358a/#b01d

**Comment by floviolleau** [comment]
The patch works fine. Thanks!

**Comment by Gunni2** [comment]
The patch works fine. Thanks!

**Comment by Caffenicotiak** [comment]
> The patch works fine. Thanks!

Same here running keepass 2.42 on Win x64

**Comment by IUSR** [comment]
Made [a fix](https://github.com/IUSR/keepasshttp/commit/b94660bd33ca95f6586a835172462fb691be7822) by adding just 2 letters.

**Comment by simonachmueller** [comment]
> 
> 
> Made [a fix](https://github.com/IUSR/keepasshttp/commit/b94660bd33ca95f6586a835172462fb691be7822) by adding just 2 letters.

Could you make a pull request here?

**Comment by bobwalker99** [comment]
Can confirm [IUSR's fix](https://github.com/pfn/keepasshttp/issues/384#issuecomment-488878568) works for me.

**Comment by CybershamanX** [comment]
Thank you for the updated file/fix. It's getting to the point where, even though I only have to dink around with this sort of thing every once in a while, I might have to start looking for something else. It's just that it takes time to remember what I have to do to get things running again (like, "Oh, yeah. I need that one file. And, hmmm, looks like this one doesn't work anymore." :P ) and it really interferes with the flow of my work. I need simple. ;) Anyway, thanks again to those who took it upon to fix the issue and then share it here. :)

**Comment by t-schroeder** [comment]
With KeePass 2.42.1 the old KeePassHttp works again.

> Improved backward compatibility with certain plugins.

**Comment by IUSR** [comment]
> Could you make a pull request here?

Sorry just saw this. I'm new to KeePass so I wasn't sure if adding the 2 letters to call the new API was sufficient, or there should be some version check to use different APIs in runtime.

**Comment by kmille** [comment]
> The patched version is available at https://keepass.info/filepool/KeePass_190501_KeePassHttp.zip
> Via this post: https://sourceforge.net/p/keepass/discussion/329221/thread/de57e6358a/#b01d

The file is not compatible with my Keepass 2.43 on Arch Linux. Does it work for you with 2.43?
