### ISSUE TITLE
404 on https://raw.github.com/pfn/keepasshttp/master/KeePassHttp.plgx

### ISSUE THREAD

**Issue by ChiefMcClane** [pfn/keepasshttp#394]
Hey

I tryed to install the plugin with Chocolatey but it failed because 404 error. 
The same problem with manuall installation
https://raw.github.com/pfn/keepasshttp/master/KeePassHttp.plgx -> 404

Log from Chocolatey :

ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://github.com/pfn/keepasshttp/raw/c2c4eb5388a02169400cba7a67be325caabdcc37/KeePassHttp.plgx'. Exception calling "GetResponse" with "0" argument(s): "The remote name could not be resolved: 'raw.githubusercontent.com'"

**Comment by tmasixpence** [comment]
same error
