### ISSUE TITLE
Wildcard/Alternative URLs support

### ISSUE THREAD

**Issue by maciejs20** [pfn/keepasshttp#68]
Hi

I have some sites that shares the same password and are using the same authentication sever. Login forms are on different URL's, but still the login and password behind them stays the same. All of those URLs are from the same DNS domain.

During the days with Windows I used to have keepass with keefox, and I could use "Advanced->String Fields->[Alternative URLs|KPRPC Alternative URLs]" inside keepass for store and match those different sites that shares the same authentication mechanism.

When switched to Ubuntu with keepassx running with mono,  keepasshttp for firefox does not offer this possibility- I can not assign many URLs to single password entry.

Is there any chance to implement this mechanism? Other way to get the same result would be to allow for wildcards in URLs.

Maciej

**Comment by ffflorian** [comment]
:+1: for multiple URL support. Some websites use different subdomains, for example `protonmail.com` and `protonmail.ch`. Would be great to match both in one entry since I can't link files and additional entries.

**Comment by SiamKreative** [comment]
Is this possible to have a wildward like `*.dev`. For development purposes, I create sites locally that I access via mydevsite.dev or wordpress.dev.

**Comment by pfn** [comment]
Not really, the search requires a "." in the name at least
